version: '3.7'

services:

  db:
    image: postgres:12-alpine
    ports:
      - '7777:7777'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Vtqyrey!Fas


