version: '3.7'

services:

  db:
    image: postgres:12-alpine
    ports:
      - '7777:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin


